version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dastgoat
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
